object = vector.o		    #def var
out: $(object)		    
	g++ -g -o vector $(object)  
test.o: test.cpp	    
	g++ -g -c -std=c++11 vector.cpp	      #tab twcie
#test.s: vector.cpp
#	g++ -S vector.cpp
clean:			
	rm *.o *.s
